server:
  port: 8081
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fedex_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: 123456789
jpa:
  hibernate:
    ddl-auto: update
  properties:
    hibernate:
      format_sql: true
      dialect: org.hibernate.dialect.MySQL8Dialect
  open-in-view: false
flyway:
  enabled: true
  locations: classpath:db/migration
mail:
  host: smtp.gmail.com
  port: 587
  username: youremail@gmail.com
  password: app-password
  properties:
    mail.smtp.auth: true
    mail.smtp.starttls.enable: true
app:
  jwt:
    secret: ThisIsA_MuchLongerAndMoreSecureSecretKeyForYourFedexProject_DoNotUseThisExactOne!
    expirationMinutes: 120
  routing:
    nearestNodeRadiusMeters: 2000
